### ISSUE TITLE
code and documentation mismatch

### ISSUE THREAD

**Issue by ginberg** [tercen/linear_mixed_model1_operator#2]
In the Bionavigator documentation of the Mixed Model 1 Way, I am reading that these are the output fields:

Name | Description 
pMain, logpMain | p-value value for the main (fixed) effect
fdr | p-value after false discovery adjustment
Top | per test rank according to p-value, if there is only one column in the calling cross-tab this value is returned as spot annotation.

But in the code it's returning pMain, logpMain and delta
```
operatorFunction <- function(aFrame){
    aLme <- try( lme( fixed = y ~ MainFactor, random = ~ 1| RepFactor   , data=aFrame ), silent = TRUE)
    
	if(!inherits(aLme, "try-error")){
      pMain = anova(aLme)[2,4]
	  delta = as.numeric(fixef(aLme)[2])
    } else {
	  pMain = NaN
	  delta = NaN
    }
	return (c(rowSeq = aFrame$rowSeq[1], colSeq = aFrame$colSeq[1], pMain=pMain, logpMain = -log10(pMain), delta = delta))
}
```
Is the code leading or should the code be adjusted to the documentation?

**Comment by rdewijn** [comment]
The code is leading

**Comment by ginberg** [comment]
ok, thanks
